[package]
name = "meshpit"
version = "0.1.0"
edition = "2024"

[dependencies]
futures-util = "0.3.31"
log = "0.4.29"
ntest = "0.9.5"
tokio = { version = "1.49.0", features = ["full"]}
tokio-tungstenite = "0.28.0"
